version: '3.8'

services:
  dev_container:
    container_name: dev_container
    image: node:16-bullseye
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"   # Puerto para la aplicación React
      - "4000:4000"   # Puerto para Apollo Server
      - "8888:8888"   # Puerto para Netlify Dev
    command: >
      sh -c "
        apt-get update &&
        apt-get install -y curl &&
        curl -fsSL https://deb.nodesource.com/setup_16.x | bash - &&
        apt-get install -y nodejs &&
        npm install -g create-react-app apollo-server graphql auth0 netlify-cli &&
        tail -f /dev/null
      "
    networks:
      - dev_network
  
  neo4j:
    container_name: neo4j
    image: neo4j:4.3.7
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/test
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge
